# Use the official PostgreSQL image from Docker Hub
FROM postgres:16.2-bullseye

# Environment variables to configure PostgreSQL
ENV POSTGRES_USER flb_user
ENV POSTGRES_PASSWORD flb_pass
ENV POSTGRES_DB flb_db
